In [1]:
from transformers import GPT2LMHeadModel

/home/htkumar/local/miniconda3/envs/gpt-2/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from datasets import load_dataset

In [ ]:
torch.cuda.is_available()

In [ ]:
torch.cuda.is_bf16_supported()

In [ ]:
torch.tril(torch.ones(8, 8)).view(1, 1, 8, 8)

In [ ]:
x = torch.arange(12).view(2, 2, 3)
x.shape

In [ ]:
q, k, v = x.chunk(3, dim=2)
q.shape, k.shape, v.shape

In [ ]:
q, k, v = x.split(1, dim=2)
q.shape, k.shape, v.shape

In [ ]:
module_dict = nn.ModuleDict(
    dict(
        module_1=nn.Linear(10, 10),
        module_2=nn.Linear(10, 10),
    )
)

In [ ]:
module_dict.keys()

In [ ]:
q.shape

In [ ]:
q.shape[::-1]

In [ ]:
a = torch.arange(6).view(2, 3)
a.shape

In [ ]:
a.t().shape

In [2]:
import tiktoken

In [10]:
a = torch.arange(12).view(3, 4).double()
a.shape, a.dtype

(torch.Size([3, 4]), torch.float64)

In [11]:
a = F.softmax(a, dim=1)
a

tensor([[0.0321, 0.0871, 0.2369, 0.6439],
        [0.0321, 0.0871, 0.2369, 0.6439],
        [0.0321, 0.0871, 0.2369, 0.6439]], dtype=torch.float64)

In [12]:
topk_probs, topk_indices = torch.topk(a, 2, dim=1)

In [13]:
topk_probs

tensor([[0.6439, 0.2369],
        [0.6439, 0.2369],
        [0.6439, 0.2369]], dtype=torch.float64)

In [14]:
topk_indices

tensor([[3, 2],
        [3, 2],
        [3, 2]])

In [15]:
b = torch.multinomial(topk_probs, 1)
b

tensor([[0],
        [0],
        [0]])

In [16]:
b.shape

torch.Size([3, 1])

In [17]:
xcol = torch.gather(topk_indices, -1, b)
xcol

tensor([[3],
        [3],
        [3]])

In [18]:
t = torch.tensor([[1, 2], [3, 4]])
torch.gather(t, 1, torch.tensor([[0, 0], [1, 0]]))

tensor([[1, 1],
        [4, 3]])

In [19]:
torch.gather(t, 0, torch.tensor([[0, 0], [1, 0]]))

tensor([[1, 2],
        [3, 2]])