In [2]:
from transformers import GPT2LMHeadModel

In [3]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from datasets import load_dataset

In [4]:
torch.cuda.is_available()

True

In [5]:
torch.cuda.is_bf16_supported()

True

In [6]:
torch.tril(torch.ones(8, 8)).view(1, 1, 8, 8)

tensor([[[[1., 0., 0., 0., 0., 0., 0., 0.],
          [1., 1., 0., 0., 0., 0., 0., 0.],
          [1., 1., 1., 0., 0., 0., 0., 0.],
          [1., 1., 1., 1., 0., 0., 0., 0.],
          [1., 1., 1., 1., 1., 0., 0., 0.],
          [1., 1., 1., 1., 1., 1., 0., 0.],
          [1., 1., 1., 1., 1., 1., 1., 0.],
          [1., 1., 1., 1., 1., 1., 1., 1.]]]])

In [7]:
x = torch.arange(12).view(2, 2, 3)
x.shape

torch.Size([2, 2, 3])

In [8]:
q, k, v = x.chunk(3, dim=2)
q.shape, k.shape, v.shape

(torch.Size([2, 2, 1]), torch.Size([2, 2, 1]), torch.Size([2, 2, 1]))

In [9]:
q, k, v = x.split(1, dim=2)
q.shape, k.shape, v.shape

(torch.Size([2, 2, 1]), torch.Size([2, 2, 1]), torch.Size([2, 2, 1]))

In [10]:
module_dict = nn.ModuleDict(
    dict(
        module_1=nn.Linear(10, 10),
        module_2=nn.Linear(10, 10),
    )
)

In [11]:
module_dict.keys()

odict_keys(['module_1', 'module_2'])

In [12]:
q.shape

torch.Size([2, 2, 1])

In [13]:
q.shape[::-1]

torch.Size([1, 2, 2])

In [14]:
a = torch.arange(6).view(2, 3)
a.shape

torch.Size([2, 3])

In [15]:
a.t().shape

torch.Size([3, 2])

In [16]:
import tiktoken

In [17]:
a = torch.arange(12).view(3, 4).double()
a.shape, a.dtype

(torch.Size([3, 4]), torch.float64)

In [18]:
a = F.softmax(a, dim=1)
a

tensor([[0.0321, 0.0871, 0.2369, 0.6439],
        [0.0321, 0.0871, 0.2369, 0.6439],
        [0.0321, 0.0871, 0.2369, 0.6439]], dtype=torch.float64)

In [19]:
topk_probs, topk_indices = torch.topk(a, 2, dim=1)

In [20]:
topk_probs

tensor([[0.6439, 0.2369],
        [0.6439, 0.2369],
        [0.6439, 0.2369]], dtype=torch.float64)

In [21]:
topk_indices

tensor([[3, 2],
        [3, 2],
        [3, 2]])

In [22]:
b = torch.multinomial(topk_probs, 1)
b

tensor([[0],
        [0],
        [0]])

In [23]:
b.shape

torch.Size([3, 1])

In [24]:
xcol = torch.gather(topk_indices, -1, b)
xcol

tensor([[3],
        [3],
        [3]])

In [25]:
t = torch.tensor([[1, 2], [3, 4]])
torch.gather(t, 1, torch.tensor([[0, 0], [1, 0]]))

tensor([[1, 1],
        [4, 3]])

In [26]:
torch.gather(t, 0, torch.tensor([[0, 0], [1, 0]]))

tensor([[1, 2],
        [3, 2]])

In [29]:
a = torch.tensor(1)
a.shape

torch.Size([])

In [30]:
a.item()

1

In [31]:
a = torch.tensor([1, 2, 3])
len(a)

3

In [2]:
import time

t0 = time.time()
t0

1719102735.5640292

In [3]:
t1 = time.time()

In [4]:
(t1 - t0)

10.980106353759766

In [5]:
time.time??

Docstring:
time() -> floating point number

Return the current time in seconds since the Epoch.
Fractions of a second may be present if the system clock provides them.
Type:      builtin_function_or_method